export let courseActions = {
  ///add course to the dp

  ADD_COURSE_BEGIN: "ADD_COURSE_BEGIN",
  ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
  ADD_COURSE_ERROR: "ADD_COURSE_ERROR",

  //Modal colse / open
  OPEN_COURSE_MODAL: "OPEN_COURSE_MODAL",
  CLOSE_COURSE_MODAL: "CLOSE_COURSE_MODAL",

  ///load courses from the dp
  LOAD_COURSE_BEGIN: "LOAD_COURSE_BEGIN",
  LOAD_COURSE_SUCCESS: "LOAD_COURSE_SUCCESS",
  LOAD_COURSE_ERROR: "LOAD_COURSE_ERROR",

  ///Delete courses from the dp

  DELETE_COURSE_BEGIN: "DELETE_COURSE_BEGIN",
  DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
  DELETE_COURSE_ERROR: "DELETE_COURSE_ERROR",
};

export let lessonActions = {
  ///add course to the dp

  ADD_LESSON_BEGIN: "ADD_LESSON_BEGIN",
  ADD_LESSON_SUCCESS: "ADD_LESSON_SUCCESS",
  ADD_LESSON_ERROR: "ADD_LESSON_ERROR",

  ///load LESSONs from the dp
  LOAD_LESSON_BEGIN: "LOAD_LESSON_BEGIN",
  LOAD_LESSON_SUCCESS: "LOAD_LESSON_SUCCESS",
  LOAD_LESSON_ERROR: "LOAD_LESSON_ERROR",

  //save lesson

  SAVE_LESSON_BEGIN: "SAVE_LESSON_BEGIN",
  SAVE_LESSON_SUCCESS: "SAVE_LESSON_SUCCESS",
  SAVE_LESSON_ERROR: "SAVE_LESSON_ERROR",

  //delete Lesson
  DELETE_LESSON_BEGIN: "DELETE_LESSON_BEGIN",
  DELETE_LESSON_SUCCESS: "DELETE_LESSON_SUCCESS",
  DELETE_LESSON_ERROR: "DELETE_LESSON_ERROR",

  //mark Down
  SET_LESSON_MARKDOWN: "SET_LESSON_MARKDOWN",
};

export let appActions = {
  TOGGLE_PREVIEW_MODE: "TOGGLE_PREVIEW_MODE",
};
